spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: genner-service
          uri: lb://genner-service
          predicates:
            - Path=/api/greeting/**, /api/genner/**
        - id: moive-route
          uri: lb://moive-service
          predicates:
            - Path=/api/moive/**
